### ISSUE TITLE
Wrong error message for `(app)`

### ISSUE THREAD

**Issue by SuzanneSoy** [AlexKnauth/kw-utils#3] opened 2016-09-03 12:00 UTC
``` racket
#lang racket
(require kw-utils/partial)
(app)
```

The code above gives the following error message:

```
app: arity mismatch;
 the expected number of arguments does not match the given number
  expected: at least 0 plus arbitrary keyword arguments
  given: 0
```

I believe it should say: `expected: at least`**1**`plus arbitrary keyword arguments`. 

The signature of `app` is `(arity+keywords (arity-at-least 1) '() #f)`, which seems correct, though.

**Comment by AlexKnauth** [comment] 2016-09-03 13:44
I can reproduce this error with a combination of `procedure-reduce-keyword-arity` and `procedure-rename`.

``` racket
#lang racket
(define f (λ (#:x [x 'x] . xs) x))
(define f* (procedure-reduce-keyword-arity f (arity-at-least 1) '() #f))
(define f** (procedure-rename f* 'f))
(f**)
;. f: arity mismatch;
; the expected number of arguments does not match the given number
;  expected: at least 0 plus arbitrary keyword arguments
;  given: 0
```

Though when I take the `procedure-rename` out of it by calling `f*` instead, it goes back to the correct error message.

``` racket
#lang racket
(define f (λ (#:x [x 'x] . xs) x))
(define f* (procedure-reduce-keyword-arity f (arity-at-least 1) '() #f))
(define f** (procedure-rename f* 'f)) ; unused
(f*)
;. f: arity mismatch;
; the expected number of arguments does not match the given number
;  expected: at least 1 plus arbitrary keyword arguments
;  given: 0
```

**Comment by AlexKnauth** [comment] 2016-09-03 14:30
Even weirder: there seems to be a `sub1` happening somewhere:

``` racket
#lang racket
(define f (λ (#:x [x 'x] . xs) x))
(define f* (procedure-reduce-keyword-arity f (arity-at-least 5) '() #f))
(define f** (procedure-rename f* 'f))
(f**)
;. f: arity mismatch;
; the expected number of arguments does not match the given number
;  expected: at least 4 plus arbitrary keyword arguments
;  given: 0
```

And again the error goes back to the normal `5` when the `procedure-rename` is taken out.

**Comment by AlexKnauth** [comment] 2016-09-03 14:42
The code for this part of the error message seems to be here:
https://github.com/racket/racket/blob/master/racket/collects/racket/private/kw.rkt#L103-L105

```
        [(arity-at-least? a)
         (let ([a (method-adjust (arity-at-least-value a))])
           (format "at least ~a" a))]
```

It calls `method-adjust`, which is defined here:
https://github.com/racket/racket/blob/master/racket/collects/racket/private/kw.rkt#L91-L96

``` racket
                 [(method-adjust)
                  (lambda (a)
                    (if (or (okm? proc)
                            (keyword-method? proc))
                        (if (zero? a) 0 (sub1 a))
                        a))]
```

And there's the `sub1`. It looks like that case of the `if` is only triggered when `proc` is some sort of keyword-method or optional-keyword-method. 

So why does it think it's a method? Does `procedure-rename` somehow convert it to a method?

**Comment by AlexKnauth** [comment] 2016-09-03 14:47
Ok. One possible cause, these `if` cases look like they're switched:
https://github.com/racket/racket/blob/master/racket/collects/racket/private/kw.rkt#L1561-L1563

``` racket
                   ((if (okm? proc)
                        make-optional-keyword-procedure
                        make-optional-keyword-method)
                    ....)
```

**Comment by AlexKnauth** [comment] 2016-09-03 15:33
I've just submitted this pull request on the Racket repo to fix this:
https://github.com/racket/racket/pull/1449

**Comment by SuzanneSoy** [comment] 2016-09-03 22:26
Thanks a lot for debugging this!

**Comment by AlexKnauth** [comment] 2016-09-05 02:09
Even when my pull request is merged though, it will only fix it for future versions of racket. I could fix it for existing versions too if I re-wrote `define-kw-proc` to avoid using `procedure-rename`.

**Comment by AlexKnauth** [comment] 2017-11-26 17:45
Fixed by https://github.com/racket/racket/pull/1449 and by https://github.com/AlexKnauth/kw-utils/commit/ac1edc0d53ab121c4e88d4aff8b44523753c325d.

**Closed as completed by AlexKnauth** 2017-11-26 17:45 UTC
